cd C:\Program Files\SmartBear\ReadyAPI-2.3.0\bin
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PTrackerWeightData=%WORKSPACE%\V1\data\TrackerWeightData.xls -PTrackerWeightResult=%WORKSPACE%\Results\%ENV%\V1\TrackerWeight\TrackerWeightResult.csv -PTrackerWeightResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\TrackerWeight\trackerWeightResponseTime.csv %WORKSPACE%\V1\script\TrackerWeight.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PTrackerWaterData=%WORKSPACE%\V1\data\TrackerWaterData.xls -PTrackerWaterResult=%WORKSPACE%\Results\%ENV%\V1\TrackerWater\TrackerWaterDataResult.csv -PTrackerWaterResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\TrackerWater\TrackerWaterResponseTime.csv %WORKSPACE%\V1\script\TrackerWater.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PTrackerMyPlanData=%WORKSPACE%\V1\data\TrackerMyPlanData.xls -PTrackerMyPlanResult=%WORKSPACE%\Results\%ENV%\V1\TrackerMyPlan\TrackerMyPlanResult.csv -PTrackerMyPlanResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\TrackerMyPlan\TrackerMyPlanResponseTime.csv %WORKSPACE%\V1\script\TrackerMyPlan.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PTrackerMeasurementData=%WORKSPACE%\V1\data\TrackerMeasurementData.xls -PTrackerMeasurementResult=%WORKSPACE%\Results\%ENV%\V1\TrackerMeasurement\TrackerMeasurementResult.csv -PTrackerMeasurementResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\TrackerMeasurement\TrackerMeasurementResponseTime.csv %WORKSPACE%\V1\script\TrackerMeasurement.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PTrackerFoodSearchData=%WORKSPACE%\V1\data\TrackerFoodSearchData.xls -PTrackerFoodSearchResult=%WORKSPACE%\Results\%ENV%\V1\TrackerFoodSearch\TrackerFoodSearchResult.csv -PTrackerFoodSearchResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\TrackerFoodSearch\TrackerFoodSearchResponseTime.csv %WORKSPACE%\V1\script\TrackerFoodSearch.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PTrackerFoodData=%WORKSPACE%\V1\data\TrackerFoodData.xls -PTrackerFoodResult=%WORKSPACE%\Results\%ENV%\V1\TrackerFood\TrackerFoodResult.csv -PTrackerFoodResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\TrackerFood\TrackerFoodResponseTime.csv %WORKSPACE%\V1\script\TrackerFood.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PTrackerExerciseData=%WORKSPACE%\V1\data\TrackerExerciseData.xls -PTrackerExerciseResult=%WORKSPACE%\Results\%ENV%\V1\TrackerExercise\TrackerExerciseResult.csv -PTrackerExerciseResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\TrackerExercise\TrackerExerciseResponseTime.csv %WORKSPACE%\V1\script\TrackerExercise.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PSearchData=%WORKSPACE%\V1\data\SearchData.xls -PSearchResult=%WORKSPACE%\Results\%ENV%\V1\Search\SearchResults.csv -PSearchResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\Search\SearchResponseTime.csv %WORKSPACE%\V1\script\Search.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PPlatformData=%WORKSPACE%\V1\data\PlatformData.xls -PPlatformResult=%WORKSPACE%\Results\%ENV%\V1\platform\platformResult.csv -PPlatformResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\platform\platformResponseTime.csv %WORKSPACE%\V1\script\Platform.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -POrganizationData=%WORKSPACE%\V1\data\OrganizationData.xls -POrganizationResult=%WORKSPACE%\Results\%ENV%\V1\Organization\OrganizationResult.csv -POrganizationResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\Organization\OrganizationResponseTime.csv %WORKSPACE%\V1\script\Organization.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMessageCenterProviderData=%WORKSPACE%\V1\data\MessageCenterProviderData.xls -PMessageCenterProviderResult=%WORKSPACE%\Results\%ENV%\V1\MessageCenterProvider\MessageCenterProviderResult.csv -PMessageCenterProviderResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MessageCenterProvider\MessageCenterProviderResponseTime.csv %WORKSPACE%\V1\script\MessageCenterProvider.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMessageCenterMemberData=%WORKSPACE%\V1\data\MessageCenterMemberData.xls -PMessageCenterMemberResult=%WORKSPACE%\Results\%ENV%\V1\MessageCenterMember\MessageCenterMemberResult.csv -PMessageCenterMemberResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MessageCenterMember\MessageCenterMemberResponseTime.csv %WORKSPACE%\V1\script\MessageCenterMember.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMessageCenterCoachData=%WORKSPACE%\V1\data\MessageCenterCoachData.xls -PMessageCenterCoachResult=%WORKSPACE%\Results\%ENV%\V1\MessageCenterCoach\MessageCenterCoachResult.csv -PMessageCenterCoachResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MessageCenterCoach\MessageCenterCoachResponseTime.csv %WORKSPACE%\V1\script\MessageCenterCoach.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PLoginData=%WORKSPACE%\V1\data\LoginData.xls -PLoginResult=%WORKSPACE%\Results\%ENV%\V1\Login\LoginResult.csv -PLoginResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\Login\LoginResponseTime.csv %WORKSPACE%\V1\script\Login.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PCreateProviderProgramAdminData=%WORKSPACE%\V1\data\CreateProviderProgramAdminData.xls -PCreateProviderProgramAdminResult=%WORKSPACE%\Results\%ENV%\V1\CreateProviderProgramAdmin\CreateProviderProgramAdminResult.csv -PCreateProviderProgramAdminResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\CreateProviderProgramAdmin\CreateProviderProgramAdminResponseTime.csv %WORKSPACE%\V1\script\CreateProviderProgramAdmin.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PCreateProviderCoachData=%WORKSPACE%\V1\data\CreateProviderCoachData.xls -PCreateProviderCoachResult=%WORKSPACE%\Results\%ENV%\V1\CreateProviderCoach\CreateProviderCoachResult.csv -PCreateProviderCoachResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\CreateProviderCoach\CreateProviderCoachResponseTime.csv %WORKSPACE%\V1\script\CreateProviderCoach.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PcontentLibraryData=%WORKSPACE%\V1\data\ContentLibraryData.xls -PcontentLibraryResult=%WORKSPACE%\Results\%ENV%\V1\ContentLibrary\ContentLibraryResult.csv -PcontentLibraryResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ContentLibrary\ContentLibraryResponseTime.csv %WORKSPACE%\V1\script\ContentLibrary.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PQSEnrollmentData=%WORKSPACE%\V1\data\QSEnrollmentData.xls -PQSEnrollmentResult=%WORKSPACE%\Results\%ENV%\V1\QSEnrollment\QSEnrollmentResult.csv -PQSEnrollmentResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\QSEnrollment\QSEnrollmentResponseTime.csv %WORKSPACE%\V1\script\QSEnrollment.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMemberDashboardResult=%WORKSPACE%\Results\%ENV%\V1\MemberDashboard\MemberDashboardResult.csv -PMemberDashboardData2=%WORKSPACE%\Results\%ENV%\V1\QSEnrollment\QSEnrollmentResult.csv -PMemberDashboardResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MemberDashboard\MemberDashboardResponseTime.csv %WORKSPACE%\V1\script\MemberDashboard.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PcontentLibraryMemResult=%WORKSPACE%\Results\%ENV%\V1\ContentLibraryMem\ContentLibraryMemResult.csv -PcontentLibraryMemResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ContentLibraryMem\ContentLibraryMemResponseTime.csv %WORKSPACE%\V1\script\ContentLibraryMem.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMemberProfileData=%WORKSPACE%\V1\data\MemberProfileData.xls -PMemberProfileResult=%WORKSPACE%\Results\%ENV%\V1\MemberProfile\MemberProfileResult.csv -PMemberProfileResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MemberProfile\MemberProfileResponseTime.csv %WORKSPACE%\V1\script\MemberProfile.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMemberSettingData=%WORKSPACE%\V1\data\MemberSettingData.xls -PMemberSettingResult=%WORKSPACE%\Results\%ENV%\V1\MemberSetting\MemberSettingResult.csv -PMemberSettingResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MemberSetting\MemberSettingResponseTime.csv %WORKSPACE%\V1\script\MemberSetting.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMemberProfileFromProviderData=%WORKSPACE%\V1\data\MemberProfileFromProviderData.xls -PMemberProfileFromProviderResult=%WORKSPACE%\Results\%ENV%\V1\MemberProfileFromProvider\MemberProfileFromProviderResult.csv -PMemberProfileFromProviderResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MemberProfileFromProvider\MemberProfileFromProviderResponseTime.csv %WORKSPACE%\V1\script\MemberProfileFromProvider.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMemberProfileFromHfopsData=%WORKSPACE%\V1\data\MemberProfileFromHfopsData.xls -PMemberProfileFromHfopsResult=%WORKSPACE%\Results\%ENV%\V1\MemberProfileFromHfops\MemberProfileFromHfopsResult.csv -PMemberProfileFromHfopsResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MemberProfileFromHfops\MemberProfileFromHfopsResponseTime.csv %WORKSPACE%\V1\script\MemberProfileFromHfops.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PproviderProfileFromPAData=%WORKSPACE%\V1\data\providerProfileFromPAData.xls -PproviderProfileFromPAResult=%WORKSPACE%\Results\%ENV%\V1\ProviderProfileFromPA\providerProfileFromPAResult.csv -PproviderProfileFromPAResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ProviderProfileFromPA\providerProfileFromPAResponseTime.csv %WORKSPACE%\V1\script\providerProfileFromPA.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PRecordSessionData=%WORKSPACE%\V1\data\RecordSessionData.xls -PRecordSessionResult=%WORKSPACE%\Results\%ENV%\V1\RecordSession\RecordSessionResult.csv -PRecordSessionResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\RecordSession\RecordSessionResponseTime.csv %WORKSPACE%\V1\script\RecordSession.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PproviderProfileCoachData=%WORKSPACE%\V1\data\providerProfileCoachData.xls -PproviderProfileCoachResult=%WORKSPACE%\Results\%ENV%\V1\providerProfileCoach\providerProfileCoachResult.csv -PproviderProfileCoachResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\providerProfileCoach\providerProfileCoachResponseTime.csv %WORKSPACE%\V1\script\providerProfileCoach.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PproviderProfilePAData=%WORKSPACE%\V1\data\ProviderProfilePAData.xls -PproviderProfilePAResult=%WORKSPACE%\Results\%ENV%\V1\providerProfilePA\providerProfilePAResult.csv -PproviderProfilePAResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\providerProfilePA\providerProfilePAResponseTime.csv %WORKSPACE%\V1\script\providerProfilePA.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PGroupSessionData=%WORKSPACE%\V1\data\GroupSessionData.xls -PGroupSessionResult=%WORKSPACE%\Results\%ENV%\V1\GroupSession\GroupSessionResult.csv -PGroupSessionResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\GroupSession\GroupSessionResponseTime.csv %WORKSPACE%\V1\script\GroupSession.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PscheduleSessionData=%WORKSPACE%\V1\data\scheduleSessionData.xls -PscheduleSessionResult=%WORKSPACE%\Results\%ENV%\V1\scheduleSession\scheduleSessionResult.csv -PscheduleSessionResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\scheduleSession\scheduleSessionResponseTime.csv %WORKSPACE%\V1\script\scheduleSession.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PprogramFromHfopsResult=%WORKSPACE%\Results\%ENV%\V1\programFromHfops\programFromHfopsResult.csv -PprogramFromHfopsResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\programFromHfops\programFromHfopsResponseTime.csv %WORKSPACE%\V1\script\programFromHfops.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PproviderProfileFromHfopsData=%WORKSPACE%\V1\data\providerProfileFromHfopsData.xls -PproviderProfileFromHfopsResult=%WORKSPACE%\Results\%ENV%\V1\providerProfileFromHfops\providerProfileFromHfopsResult.csv -PproviderProfileFromHfopsResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\providerProfileFromHfops\providerProfileFromHfopsResponseTime.csv %WORKSPACE%\V1\script\providerProfileFromHfops.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PProviderDashboardData=%WORKSPACE%\V1\data\ProviderDashboardData.xls -PProviderDashboardResult=%WORKSPACE%\Results\%ENV%\V1\ProviderDashboard\ProviderDashboardResult.csv -PProviderDashboardResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ProviderDashboard\ProviderDashboardResponseTime.csv %WORKSPACE%\V1\script\ProviderDashboard.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PReenrollmentProcessData=%WORKSPACE%\V1\data\ReenrollmentProcessData.xls -PReenrollmentProcessResult=%WORKSPACE%\Results\%ENV%\V1\ReenrollmentProcess\ReenrollmentProcessResult.csv -PReenrollmentProcessResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ReenrollmentProcess\ReenrollmentProcessResponseTime.csv %WORKSPACE%\V1\script\ReenrollmentProcess.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PReenrollmentCancelResult=%WORKSPACE%\Results\%ENV%\V1\ReenrollmentCancel\ReenrollmentCancelResult.csv -PReenrollmentCancelResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ReenrollmentCancel\ReenrollmentCancelResponseTime.csv %WORKSPACE%\V1\script\ReenrollmentCancel.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PClassesFromHfopsData=%WORKSPACE%\V1\data\ClassesFromHfopsData.xls -PClassesFromHfopsResult=%WORKSPACE%\Results\%ENV%\V1\ClassesFromHfops\ClassesFromHfopsResult.csv -PClassesFromHfopsResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ClassesFromHfops\ClassesFromHfopsResponseTime.csv %WORKSPACE%\V1\script\ClassesFromHfops.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PClassSearchFromProviderData=%WORKSPACE%\V1\data\ClassSearchFromProviderData.xls -PClassSearchFromProviderResult=%WORKSPACE%\Results\%ENV%\V1\ClassSearchFromProvider\ClassSearchFromProviderResult.csv -PClassSearchFromProviderResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ClassSearchFromProvider\ClassSearchFromProviderResponseTime.csv %WORKSPACE%\V1\script\ClassSearchFromProvider.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PAddCoachAvailabilityData=%WORKSPACE%\V1\data\AddCoachAvailabilityData.xls -PAddCoachAvailabilityResult=%WORKSPACE%\Results\%ENV%\V1\AddCoachAvailability\AddCoachAvailabilityResult.csv -PAddCoachAvailabilityResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\AddCoachAvailability\AddCoachAvailabilityResponseTime.csv %WORKSPACE%\V1\script\AddCoachAvailability.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PRemoveCoachAvailabilityData=%WORKSPACE%\\Results\%ENV%\V1\AddCoachAvailability\AddCoachAvailabilityResult.csv -PRemoveCoachAvailabilityResult=%WORKSPACE%\Results\%ENV%\V1\RemoveCoachAvailability\RemoveCoachAvailabilityResult.csv -PRemoveCoachAvailabilityResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\RemoveCoachAvailability\RemoveCoachAvailabilityResponseTime.csv %WORKSPACE%\V1\script\RemoveCoachAvailability.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PClassSearchData=%WORKSPACE%\V1\data\ClassSearchData.xls -PClassSearchResult=%WORKSPACE%\Results\%ENV%\V1\ClassSearch\ClassSearchResult.csv -PClassSearchResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ClassSearch\ClassSearchResponseTime.csv %WORKSPACE%\V1\script\ClassSearch.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PClassReassignData=%WORKSPACE%\V1\data\ClassReassignData.xls -PClassReassignResult=%WORKSPACE%\Results\%ENV%\V1\ClassReassign\ClassReassignResult.csv -PClassReassignResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ClassReassign\ClassReassignResponseTime.csv %WORKSPACE%\V1\script\ClassReassign.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PClassApproveData=%WORKSPACE%\V1\data\ClassApproveData.xls -PClassApproveResult=%WORKSPACE%\Results\%ENV%\V1\ClassApprove\ClassApproveResult.csv -PClassApproveResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\ClassApprove\ClassApproveResponseTime.csv %WORKSPACE%\V1\script\ClassApprove.xml
cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PclaimsAPIdata=%WORKSPACE%\V1\data\claimsAPIData.xls -PclaimsAPIresponse=%WORKSPACE%\Results\%ENV%\V1\claimsAPI\claimsAPIResult.csv %WORKSPACE%\V1\script\claimsAPI.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PCreateMemberData=%WORKSPACE%\V1\data\CreateMemberData.xls -PCreateMemberResult=%WORKSPACE%\Results\%ENV%\V1\CreateMember\CreateMemberResult.csv -PCreateMemberResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\CreateMember\CreateMemberResponseTime.csv %WORKSPACE%\V1\script\CreateMember.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PCreateMemberData=%WORKSPACE%\V1\data\CreateMemberForCustomizationData.xls -PCreateMemberResult=%WORKSPACE%\Results\%ENV%\V1\MemberCustomization\CreateMemberForCustomizationRes.csv -PCreateMemberResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MemberCustomization\CreateMemberForCustomizationResponseTime.csv %WORKSPACE%\V1\script\CreateMember.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMemberCustomizationData=%WORKSPACE%\V1\data\MemberCustomizationData.xls -PMemberCustomizationResult=%WORKSPACE%\Results\%ENV%\V1\MemberCustomization\MemberCustomizationResult.csv -PMemberCustomizationData2=%WORKSPACE%\Results\%ENV%\V1\MemberCustomization\CreateMemberForCustomizationRes.csv -PMemberCustomizationResponseTime=%WORKSPACE%\ResponseTime\%ENV%\V1\MemberCustomization\MemberCustomizationResponseTime.csv %WORKSPACE%\V1\script\MemberCustomization.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -P1on1SessionData=%WORKSPACE%\V2\data\%ENV%\1on1SessionMemberData.xls -P1on1SessionResponse=%WORKSPACE%\Results\%ENV%\V2\1on1SessionMember\1on1SessionMemberResponse.csv %WORKSPACE%\V2\script\1on1SessionMember.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -P1on1SessionProMgmtData=%WORKSPACE%\V2\data\%ENV%\1on1SessionProviderMgmtData.xls -P1on1SessionProviderMgmtResponse=%WORKSPACE%\Results\%ENV%\V2\1on1SessionProviderMgmt\1on1SessionProviderMgmtREs.csv %WORKSPACE%\V2\script\1on1SessionProviderHFOPS.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PCreategroupSessionData=%WORKSPACE%\V2\data\%ENV%\CreateGroupSessionData.xls -PCreategroupSessionResponse=%WORKSPACE%\Results\%ENV%\V2\CreateGroupSession\CreateGroupSessionREs.csv %WORKSPACE%\V2\script\CreateGroupSession.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PcreateMemDataSheet=%WORKSPACE%\V2\data\%ENV%\CreateMemberData.xls -PCreateMemResponse=%WORKSPACE%\Results\%ENV%\V2\CreateMember\CreateMemberResponse.csv %WORKSPACE%\V2\script\CreateMember.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PcreateMemDataSheet=%WORKSPACE%\V2\data\%ENV%\CreateMember.xls -PCreateMemResponse=%WORKSPACE%\Results\%ENV%\V2\CreateMemberForTracker\CreateMemberForTracker.csv %WORKSPACE%\V2\script\CreateMember.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PmemDashbrdSrc=%WORKSPACE%\V2\data\%ENV%\SetPlacementDateData.xls -PmemDashboardRes=%WORKSPACE%\Results\%ENV%\V2\SetPlacementDate\SetPlacementDateRes.csv -PgetMemSrc=%WORKSPACE%\Results\%ENV%\V2\CreateMemberForTracker\CreateMemberForTracker.csv %WORKSPACE%\V2\script\SetPlacementDate.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PtrackerSource=%WORKSPACE%\V2\data\%ENV%\TrackerData.xls -PtrackerResponse=%WORKSPACE%\Results\%ENV%\V2\tracker\trackerRes.csv -PcreatedMemSrc=%WORKSPACE%\Results\%ENV%\V2\CreateMemberForTracker\CreateMemberForTracker.csv %WORKSPACE%\V2\script\Tracker.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PauthInputSheet=%WORKSPACE%\V2\data\%ENV%\LoginData.xls -PauthenticationResponse=%WORKSPACE%\Results\%ENV%\V2\Login\LoginRes.csv %WORKSPACE%\V2\script\Login.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PmemSettingSource=%WORKSPACE%\V2\data\%ENV%\MemberSettingsData.xls -PmemSettingResponse=%WORKSPACE%\Results\%ENV%\V2\MemberSettings\MemberSettingsData.csv -PgetCreatedMember=%WORKSPACE%\Results\%ENV%\V2\CreateMember\CreateMemberResponse.csv %WORKSPACE%\V2\script\MemberSettings.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PphotosMemberSource=%WORKSPACE%\V2\data\%ENV%\PhotosMemberData.xls -PphotosMemberResponse=%WORKSPACE%\Results\%ENV%\V2\Photos\PhotosMemberREs.csv %WORKSPACE%\V2\script\PhotosMember.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PPhotosSource=%WORKSPACE%\V2\data\%ENV%\PhotosMgmtAndProviderData.xls -PPhotosResponse=%WORKSPACE%\Results\%ENV%\V2\Photos\PhotosMgmtAndProviderREs.csv %WORKSPACE%\V2\script\PhotosMgmtAndProvider.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PmemberDetailPracData=%WORKSPACE%\V2\data\%ENV%\MemberDetailPractitonerData.xls -PmemberDetailPracResponse=%WORKSPACE%\Results\%ENV%\V2\MemberDetails\MemberDetailPractitonerREs.csv %WORKSPACE%\V2\script\MemberDetailPractitoner.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PMemDetailsCoachPAData=%WORKSPACE%\V2\data\%ENV%\MemberDetailsCoachPAData.xls -PMemDetailsCoachPAResponse=%WORKSPACE%\Results\%ENV%\V2\MemberDetails\MemberDetailsCoachPAREs.csv %WORKSPACE%\V2\script\MemberDetailsCoachAndPA.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PmemDetailHFOPS=%WORKSPACE%\V2\data\%ENV%\MemberDetailHFOPSData.xls -PmemDetailmgmtResponse=%WORKSPACE%\Results\%ENV%\V2\MemberDetails\MemberDetailHFOPSREs.csv %WORKSPACE%\V2\script\MemberDetailsHFOPS.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -Ppromgsource=%WORKSPACE%\V2\data\%ENV%\CreateProviderData.xls -PcreateProviderResponse=%WORKSPACE%\Results\%ENV%\V2\CreateProvider\CreateProviderRes.csv %WORKSPACE%\V2\script\CreateProvider.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PmsgCentrData=%WORKSPACE%\V2\data\%ENV%\MessageCenterCoachData.xls -PmsgCntrCoachResult=%WORKSPACE%\Results\%ENV%\V2\messageCenter\messageCenterCoach.csv %WORKSPACE%\V2\script\MessageCenterCoach.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PmessageCenterData=%WORKSPACE%\V2\data\%ENV%\MessageCenterPaData.xls -PmessageCenterResult=%WORKSPACE%\Results\%ENV%\V2\MessageCenter\MessageCenterPa.csv %WORKSPACE%\V2\script\MessageCenterPa.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PsearchMgmtData=%WORKSPACE%\V2\data\%ENV%\SearchMgmtData.xls -PsearchMgmtResponse=%WORKSPACE%\Results\%ENV%\V2\Search\SearchMgmtRes.csv %WORKSPACE%\V2\script\SearchMgmt.xml
::cmd.exe /C testrunner.bat "-RJUnit-Style HTML Report" -E%ENV% -I -PsearchProviderData=%WORKSPACE%\V2\data\%ENV%\SearchProviderData.xls -PsearchProviderResponse=%WORKSPACE%\Results\%ENV%\V2\Search\SearchProviderREs.csv %WORKSPACE%\V2\script\SearchProvider.xml
cd C:\APIFunctionalTest\qa-automation-api\API_report
java -jar -Dzado.reporter.config=C:\APIFunctionalTest\qa-automation-api\API_report\zado%ENV%.properties -DlogfileLoc=C:\log ZA_API.jar
